elasticsearch:
  image: elasticsearch:latest
  command: elasticsearch -Des.network.host=0.0.0.0 -Dindices.fielddata.cache.size=4%
  environment:
    - ES_HEAP_SIZE=50m
  ports:
    - "9200:9200"
    - "9300:9300"
logstash:
  image: logstash:latest
  command: logstash -f /etc/logstash/conf.d/logstash.conf
  environment:
    - LS_HEAP_SIZE=50m
    - LS_JAVA_OPTS=-Xms50m
  volumes:
    - ./logstash/config:/etc/logstash/conf.d
  ports:
    - "9999:9999/udp"
  links:
    - elasticsearch
kibana:
  image: jsdevops/kibana:latest
  volumes:
    - ./kibana/config/kibana.yml:/opt/kibana/config/kibana.yml
  ports:
    - "5601:5601"
  links:
    - elasticsearch
